In [ ]:
import numpy as np

In [ ]:
# 1) Write a program to create a 5 dimensional array with all zeros and ones

In [ ]:
arr1 = np.random.choice([1,0], size=[3,4,3,4,3])
arr1

array([[[[[0, 1, 1],
          [1, 0, 0],
          [0, 1, 0],
          [1, 1, 0]],

         [[1, 1, 0],
          [0, 1, 1],
          [0, 1, 0],
          [1, 0, 0]],

         [[0, 0, 1],
          [1, 0, 0],
          [1, 0, 1],
          [0, 0, 0]]],


        [[[0, 0, 1],
          [0, 1, 0],
          [1, 1, 1],
          [0, 1, 1]],

         [[1, 0, 1],
          [0, 1, 0],
          [1, 1, 0],
          [1, 0, 1]],

         [[1, 1, 1],
          [0, 1, 0],
          [1, 0, 1],
          [1, 0, 0]]],


        [[[0, 0, 1],
          [1, 1, 1],
          [0, 1, 1],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          [0, 1, 0]],

         [[1, 1, 1],
          [1, 0, 0],
          [0, 1, 1],
          [1, 0, 0]]],


        [[[0, 0, 0],
          [0, 0, 1],
          [1, 1, 1],
          [0, 0, 1]],

         [[1, 0, 0],
          [0, 0, 0],
          [0, 0, 1],
          [1, 1, 0]],

         [[1, 1, 0],
          [1, 1, 0],
      

In [ ]:
# 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [ ]:
arr2 = np.array([[0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1],[5,5,5,5,5,5,5,5,5,5]])
arr2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
# 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [ ]:
arr3 = np.random.randint(10,21,size=[3,4])
arr3

array([[11, 15, 16, 13],
       [13, 12, 14, 15],
       [13, 13, 19, 16]])

In [ ]:
# 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [ ]:
arr4 = np.diag([0,1,2,3,4,5,6,7,8,9])
arr4

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [ ]:
# 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [ ]:
arr5 = np.arange(1,17).reshape(4,4)
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr5[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [ ]:
# 6) Write a program to reverse an array (the first element becomes the last).


In [ ]:
arr6 = np.arange(12,28)
print(arr6)
print(arr6[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
[27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [ ]:
# 7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [ ]:
arr7 = np.arange(1,101).reshape(10,10)
arr8=arr7[3:8]
arr8[arr8%5==0]



array([35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [ ]:
# 8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [ ]:
arr9 = np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])
arr9

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [ ]:
# 9) Write a program to create a checkerboard pattern .Don't use default array function Checkerboard pattern:

In [ ]:
arr10 = np.arange(1,65).reshape(8,8)
arr = np.arange(1,65,2)
p=np.repeat(arr,2).reshape(8,8)
arr10-p


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# 10) Write a program to find common values between two arrays.

In [ ]:
arr11 = np.array([10,20,40,60])
arr12 = np.array([10,30,40,50])
set(arr12).intersection(set(arr11))

{10, 40}

In [ ]:
# 11) Write a program to create an array 2d array and then reshape into 1d array


In [ ]:
print(arr9)
arr9.flatten()

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1])

In [ ]:
# 12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [5]:
def createArray(dim):
  if dim == 1:
    def oneDim():
      lst = []
      for i in range(0,5):
        lst.append(int(input("Enter number ")))
      print(lst)
    oneDim()
  if dim == 2:
    def twoDim():
      for i in range(0,5):
        for j in range(0,5):
          if j<i:
            print([j,i,j])
    twoDim()


In [6]:
createArray(1)

Enter number 5
Enter number 3
Enter number 8
Enter number 2
Enter number 1
[5, 3, 8, 2, 1]


In [7]:
createArray(2)

[0, 1, 0]
[0, 2, 0]
[1, 2, 1]
[0, 3, 0]
[1, 3, 1]
[2, 3, 2]
[0, 4, 0]
[1, 4, 1]
[2, 4, 2]
[3, 4, 3]
